apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq01
  labels:
    app: vpromq01
spec:
  selector:
    matchLabels:
      app: vpromq01
  replicas: 1
  template:
    metadata:
      labels:
        app: vpromq01
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vprofile-role"
        vault.hashicorp.com/agent-inject-secret-rmq-pass: "secret/data/vprofile"
        vault.hashicorp.com/agent-inject-template-rmq-pass: |
          {{- with secret "secret/data/vprofile" -}}
          {{- $encrypted := .Data.data.rmq-pass -}}
          {{- with secret "transit/decrypt/vprofile-key" "ciphertext"=$encrypted -}}
          {{ .Data.plaintext | base64decode }}
          {{- end -}}
          {{- end -}}
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: vpromq01
        image: rabbitmq
        ports:
        - name: vpromq01-port
          containerPort: 15672
        env: 
         - name: RABBITMQ_DEFAULT_PASS
           value: "file"
        command: ["/bin/sh"]
        args: 
          - -c
          - |
            export RABBITMQ_DEFAULT_PASS=$(cat /vault/secrets/rmq-pass)
            docker-entrypoint.sh rabbitmq-server
        volumeMounts:
        - name: vault-secrets
          mountPath: /vault/secrets
          readOnly: true
      volumes:
      - name: vault-secrets
        emptyDir: {}